name: VibeMemo
options:
  bundleIdPrefix: com.doiya
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  
settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    
targets:
  VibeMemo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: VibeMemo
        type: group
    settings:
      base:
        INFOPLIST_FILE: VibeMemo/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.doiya.vibememo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: VibeMemo/Info.plist
      properties:
        CFBundleDisplayName: VibeMemo
        CFBundleName: VibeMemo
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "VibeMemo 需要访问麦克风来录制语音笔记和对话"
        NSFaceIDUsageDescription: "VibeMemo 使用 Face ID 保护你的隐私数据"
        NSSpeechRecognitionUsageDescription: "VibeMemo 使用语音识别将你的录音转换为文字"
        ITSAppUsesNonExemptEncryption: false
    entitlements:
      path: VibeMemo/VibeMemo.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.doiya.vibememo
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.doiya.vibememo
